name: Прогрев кеша платформы

on:
  workflow_dispatch:

jobs:
  warm-8317:
    name: Кеш 8.3.17.2760
    runs-on: ubuntu-22.04
    steps:
      - name: Установка 1С:Предприятие 8.3.17.2760
        uses: 1CDevFlow/onec-setup-action@main
        with:
          type: onec
          onec_version: 8.3.17.2760
          cache: true
        env:
          ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
          ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
        timeout-minutes: 30

  warm-8327:
    name: Кеш 8.3.27.1989
    runs-on: ubuntu-22.04
    steps:
      - name: Установка 1С:Предприятие 8.3.27.1989
        uses: 1CDevFlow/onec-setup-action@main
        with:
          type: onec
          onec_version: 8.3.27.1989
          cache: true
        env:
          ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
          ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
        timeout-minutes: 30
